#! /usr/bin/env python3

#  This script takes a list of uuid of Photos and adds ALL
#  to a Album that already exists in Photos.app


def move(lib_dir, album_name, uuid_list):
    # Connect to DB
    db_path = os.path.join(lib_dir, 'database')
    main_db_path = os.path.join(db_path, 'photos.db')
    proxy_db_path = os.path.join(db_path, 'photos.db')

    try:
        main_db = sqlite3.connect(main_db_path)
        main_db.row_factory = sqlite3.Row

    except sqlite3.Error as erro:
        print("Problem connecting to Database: ", main_db_path)
        print(" Error: ", erro)
        sys.exit(1)

    try:
        dbcursor = main_db.cursor()
        dbcursor.execute('select modelId from RKAlbum where name = ?', album_name)
    except sqlite3.Error as erro:
        print("Problem on Database: ", main_db_path)
        print(" Error: ", erro)
        sys.exit(1)

    # first, discover AlbumID.


# ----------------------------------------------------------------------------------------
if __name__ == '__main__':
    # Options parsed from command line
    parser = ArgumentParser()
    parser.add_argument('library_dir', help='Path of Photos App Library to check')
    parser.add_argument('album', help='The album name to send all photos to (MUST EXIST)')
    parser.add_argument('uuid_list', help='The Photo uuid list, generated bym missing script. One each line.')
    args = parser.parse_args()

    print("Moving Photos of Library: ", args.library_dir)
    move(args.library_dir, args.album, args.uuid_list)
