#! /usr/bin/env python3


#     This script reads a CSV file containind UUIDs and PathNames,
#  generated by check_photos_library and a directory containing the
#  photos missing.
#
#     With those, it copies back the photos to original location. The
#  photos on the directory must have the same name as original that's
#  missing on Photos Library.
#

CRED = '\033[31m'
CGREEN = '\033[32m'
CEND = '\033[0m'

# Usage ./restore_from_directory.py <source_img_dir> <csv_file> <library_dir>
if __name__ == '__main__':
    # Options parsed from command line
    parser = ArgumentParser()
    parser.add_argument('-v', '--verbose', action="store_true", default=False, help='Print All Check Files on Screen')
    parser.add_argument('-p', '--path', action="store_true", default=False, help='Store UUIDs with Path')
    parser.add_argument('library_dir', help='Path of Photos App Library to check')
    parser.add_argument('output_file', help='Output file with UUIDs found.')
    args = parser.parse_args()

    print("Checking Library: ", args.library_dir)
    copyback(args.verbose, args.path, True, args.library_dir, args.output_file)
